### PR TITLE
vendor & lint & docker image & rlimit_mem

### PR DESCRIPTION
**Pull request by htfy96**
1. Save dependencies under `/vendor` directory. Golang 1.6 or above can add these directory into search path automatically. Legacy versions of golang may require `godep` to add `vendor` into load path.
2. lint with `go vet` and `go lint`
3. Add `Dockerfile` and URL to built image
4. Implemented `rlimit_mem` field for `RsyncWorker`

### CODE REVIEW

**Comment by shanzi** [comment]
You'd better use `git submodule` or [govendor](https://github.com/kardianos/govendor) to maintain those dependencies instead of commit them directly into your repo.

I know golang's package management sucks, but not bad enough to bundle dependencies along with your code :)

**Comment by htfy96** [comment]
@shanzi This is a very controversial topic and there already exist several debates over it[0][1].   Actually if you look into [`govendor`](https://github.com/kardianos/govendor)'s source tree, you'll find `vendor` directory which contains all dependencies, so it does in many other projects: many package management tools(godep, govendor, glide, etc.) have first-class checked-in vendor support. Though I admit that checked-in vendor seems like a bad idea, it might still be better than something considered only as an alternative or fallback choice by so many tools.

[0]: https://www.reddit.com/r/golang/comments/471ckr/how_to_fix_the_go_package_management_problem/
[1]: https://blog.gopheracademy.com/advent-2015/vendor-folder/

**Comment by htfy96** [comment]
@shanzi Rebased with changed author.

**Comment by shanzi** [comment]
LGTM

**Pull request merged**
